#!/bin/sh

APPDIR=$(dirname "$0")
java -Xms64m -Xmx1024m -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/equinox.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/proscene.jar:$APPDIR/lib/itext.jar:$APPDIR/lib/pdf.jar" equinox "$@"
